// The code for this file was generated by AI
import Link from 'next/link'
import { useCreateQueryString } from '@/hooks/useCreateQueryString'
import '@/components/Blog/Pagination/index.css'

interface BlogPaginationProps {
  totalPages: number
  currentPage: number
}

const BlogPagination = ({ totalPages, currentPage }: BlogPaginationProps) => {
  const createQueryString = useCreateQueryString()

  return (
    <div className='blog-pagination'>
      {Array.from({ length: totalPages }, (_, i) => i + 1).map((page) => (
        <Link
          key={page}
          href={`/blog?${createQueryString({ page: page.toString() })}`}
          className={`blog-pagination__link ${
            page === currentPage ? 'active' : ''
          }`}
        >
          {page}
        </Link>
      ))}
    </div>
  )
}

export default BlogPagination
