// The code for this file was generated by AI
import { useSearchParams } from 'next/navigation'

export const useCreateQueryString = () => {
  const urlSearchParams = useSearchParams()

  const createQueryString = (newParams: Record<string, string>) => {
    const params = new URLSearchParams(urlSearchParams.toString())
    Object.entries(newParams).forEach(([key, value]) => {
      if (value) {
        params.set(key, value)
      } else {
        params.delete(key)
      }
    })
    return params.toString()
  }

  return createQueryString
}
