// The code for this file was generated by AI

export interface WordPressPost {
  id: number
  title: {
    rendered: string
  }
  content: {
    rendered: string
  }
  excerpt: {
    rendered: string
  }
  date: string
  slug: string
  featured_media: number
}

export interface SearchParamsType {
  page: string | null
  categories: string | null
  orderby: 'date' | 'title' | null
  order: 'asc' | 'desc' | null
}

export type PaginationType = {
  total: number
  totalPages: number
  currentPage: number
}
