// The code for this file was generated by AI
import { Metadata } from 'next'
import Post from '@/components/Post'

type Props = {
  params: Promise<{ slug: string }>
  searchParams: Promise<{ [key: string]: string | string[] | undefined }>
}

async function getPost(slug: string) {
  const res = await fetch(
    `${process.env.NEXT_PUBLIC_API_ENDPOINT_WORDPRESS}/posts?slug=${slug}`,
    {
      next: { revalidate: 3600 }
    }
  )

  if (!res.ok) throw new Error('Failed to fetch post')
  const posts = await res.json()

  if (!posts.length) {
    throw new Error('Post not found')
  }

  return posts[0]
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { slug } = await params
  const post = await getPost(slug)

  return {
    title: `${post.title.rendered} | Tech Blog`,
    description: post.excerpt?.rendered.replace(/<[^>]+>/g, '').slice(0, 160)
  }
}

export default async function PostPage({ params }: Props) {
  const { slug } = await params

  return (
    <main className='container'>
      <Post slug={slug} />
    </main>
  )
}
