// The code for this file was generated by AI
import Link from 'next/link'

export default function Home() {
  return (
    <div
      style={{
        minHeight: '100vh',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center'
      }}
    >
      <Link
        href='/blog'
        style={{
          padding: '16px 32px',
          backgroundColor: '#2563eb',
          color: 'white',
          borderRadius: '8px',
          fontSize: '20px',
          textDecoration: 'none',
          boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)',
          transition: 'background-color 0.2s ease',
          cursor: 'pointer'
        }}
      >
        Visit Blog
      </Link>
    </div>
  )
}
