// The code for this file was generated by AI
import Link from 'next/link'
import Image from 'next/image'
import { WordPressPost } from '@/types/blog'
import { sanitize } from '@/helpers/sanitize'
import { useFetchData } from '@/hooks/useFetchData'
import '@/components/Blog/Card/index.css'

interface BlogCardProps {
  post: WordPressPost
}

type Media = {
  source_url: string
  alt_text: string
}

const BlogCard = ({ post }: BlogCardProps) => {
  // ****************** The beginning of the code I wrote :) ******************

  const endpoint = `${process.env.NEXT_PUBLIC_API_ENDPOINT_WORDPRESS}/media/${post.featured_media}`
  const { data: media, isLoading } = useFetchData<Media>(endpoint)

  // ****************** The end of the code I wrote. ******************

  return (
    <article className='blog__card'>
      <Link href={`/blog/${post.slug}`} className='blog__card-link'>
        <div className='blog__card-image'>
          {media && !isLoading ? (
            <Image
              src={media.source_url}
              alt={media.alt_text || ''}
              width={410}
              height={245}
              className='blog__card-img'
              priority={false}
            />
          ) : (
            <div className='blog__card-placeholder' />
          )}
        </div>
        <div className='blog__card-content'>
          <h2
            className='blog__card-title'
            dangerouslySetInnerHTML={sanitize(post.title.rendered)}
          />
          <div
            className='blog__card-excerpt'
            dangerouslySetInnerHTML={sanitize(post.excerpt?.rendered)}
          />
          <time className='blog__card-date'>
            {new Date(post.date).toLocaleDateString('en-US')}
          </time>
        </div>
      </Link>
    </article>
  )
}

export default BlogCard
