'use client'

// The code for this file was generated by AI
import { useSearchParams } from 'next/navigation'
import BlogCard from '@/components/Blog/Card'
import BlogSort from '@/components/Blog/Sort'
import BlogCategories from '@/components/Blog/Categories'
import BlogPagination from '@/components/Blog/Pagination'
import { useFilterList } from '@/hooks/useFilterList'
import { SearchParamsType } from '@/types/blog'
import '@/components/Blog/index.css'

const Blog = () => {
  const urlSearchParams = useSearchParams()
  const searchParams: SearchParamsType = {
    page: urlSearchParams.get('page'),
    categories: urlSearchParams.get('categories'),
    orderby: urlSearchParams.get('orderby') as 'date' | 'title',
    order: urlSearchParams.get('order') as 'asc' | 'desc'
  }
  // ****************** The beginning of the code I wrote :) ******************

  const { posts, isLoading, pagination } = useFilterList(searchParams)

  // ****************** The end of the code I wrote. ******************

  return (
    <section className='blog'>
      <div className='blog__filters'>
        <BlogSort orderby={searchParams.orderby} order={searchParams.order} />
      </div>

      <BlogCategories currentCategories={searchParams.categories} />

      <div className='blog__grid'>
        {isLoading ? (
          <p>Loading posts...</p>
        ) : (
          posts?.map((post) => <BlogCard key={post.id} post={post} />)
        )}
      </div>

      {isLoading ? (
        <p>Loading pagination...</p>
      ) : (
        pagination.totalPages > 1 && (
          <BlogPagination
            totalPages={pagination.totalPages}
            currentPage={pagination.currentPage}
          />
        )
      )}
    </section>
  )
}
export default Blog
