// The code for this file was generated by AI
import { useRouter } from 'next/navigation'
import { useCreateQueryString } from '@/hooks/useCreateQueryString'
import { useFetchData } from '@/hooks/useFetchData'
import { SearchParamsType } from '@/types/blog'
import '@/components/Blog/Categories/index.css'

interface Category {
  id: number
  name: string
  count: number
}

interface BlogCategoriesProps {
  currentCategories: SearchParamsType['categories']
}
const BlogCategories = ({ currentCategories }: BlogCategoriesProps) => {
  // ****************** The beginning of the code I wrote :) ******************

  const endpoint = `${process.env.NEXT_PUBLIC_API_ENDPOINT_WORDPRESS}/categories`
  const { data: categories, isLoading } = useFetchData<Category[]>(endpoint)

  // ****************** The end of the code I wrote. ******************
  const router = useRouter()
  const createQueryString = useCreateQueryString()

  const handleCategoryClick = (categoryId: number) => {
    const _currentCategories = currentCategories?.split(',') || []
    let newCategories: string[]

    if (_currentCategories.includes(String(categoryId))) {
      newCategories = _currentCategories.filter(
        (id) => id !== String(categoryId)
      )
    } else {
      newCategories = [..._currentCategories, String(categoryId)]
    }

    const queryString = createQueryString({
      categories: newCategories.length ? newCategories.join(',') : '',
      page: '1'
    })

    router.push(`/blog?${queryString}`)
  }

  const selectedCategories = currentCategories?.split(',') || []

  return (
    <div className='blog-categories'>
      {isLoading ? (
        <p>Loading categories...</p>
      ) : (
        categories?.map((category) => (
          <button
            key={category.id}
            onClick={() => handleCategoryClick(category.id)}
            className={`blog-categories__item ${
              selectedCategories.includes(String(category.id)) ? 'active' : ''
            }`}
          >
            {category.name} ({category.count})
          </button>
        ))
      )}
    </div>
  )
}

export default BlogCategories
