'use client'

// The code for this file was generated by AI
import '@/components/Post/index.css'
import { sanitize } from '@/helpers/sanitize'
import { useFetchData } from '@/hooks/useFetchData'
import { WordPressPost } from '@/types/blog'

interface PostProps {
  slug: string
}

const Post = ({ slug }: PostProps) => {
  // ****************** The beginning of the code I wrote :) ******************
  const endpoint = `${process.env.NEXT_PUBLIC_API_ENDPOINT_WORDPRESS}/posts?slug=${slug}`
  const { data, isLoading } = useFetchData<WordPressPost[]>(endpoint)
  const post = data?.[0]

  if (isLoading) return <p>Loading...</p>
  if (!post) return <h1>Post not found</h1>
  // ****************** The end of the code I wrote. ******************

  return (
    <article className='post'>
      <header className='post__header'>
        <h1
          className='post__title'
          dangerouslySetInnerHTML={sanitize(post.title.rendered)}
        />
        <div className='post__meta'>
          <time>{new Date(post.date).toLocaleDateString('en-US')}</time>
        </div>
      </header>

      <div
        className='post__content'
        dangerouslySetInnerHTML={sanitize(post.content.rendered)}
      />
    </article>
  )
}

export default Post
