// The code for this file was generated by AI
import '@/components/Post/Post.css'

interface PostProps {
  post: {
    title: {
      rendered: string
    }
    content: {
      rendered: string
    }
    date: string
  }
}

const Post = ({ post }: PostProps) => {
  return (
    <article className='post'>
      <header className='post__header'>
        <h1
          className='post__title'
          dangerouslySetInnerHTML={{ __html: post.title.rendered }}
        />
        <div className='post__meta'>
          <time>{new Date(post.date).toLocaleDateString('en-US')}</time>
        </div>
      </header>

      <div
        className='post__content'
        dangerouslySetInnerHTML={{ __html: post.content.rendered }}
      />
    </article>
  )
}

export default Post
