// The code for this file was generated by AI
import { Metadata } from 'next'
import Blog from '@/components/Blog'
import { Suspense } from 'react'

export const metadata: Metadata = {
  title: 'Blog | Tech Insights',
  description: 'Latest articles about technology and development'
}

export default async function BlogPage() {
  return (
    <main className='container'>
      <Suspense fallback={<div>Loading...</div>}>
        <Blog />
      </Suspense>
    </main>
  )
}
